[package]
name = "lu_cfg_home"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdg = "2.4.0"
lu_error = { version = "0.1.0", path = "../lu_error" }
