# The keywords of our language.
keywords = [
    "let",
    "fn",
    "elif",
    "else",
    "if",
    "while",
    "end",
]

# Literal data embedded in the source.
literals = [
    ["number", "[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)"],
]

# Symbols alongside names for them.
punctuation = [
    ['(', "left parenthesis"],
    [')', "right parenthesis"],
    ['{', "left curly brackets"],
    ['}', "right curly brackets"],
    ['[', "left rectangular brackets"],
    [']', "right rectangular brackets"],
    ['+', "plus sign"],
    ['-', "minus sign"],
    ['*', "mult sign"],
    ['/', "div sign"],
    ['<', "less than sign"],
    ['<=', "less or equal sign"],
    ['==', "equality sign"],
    ['!=', "inequality sign"],
    ['>', "bigger than sign"],
    ['>=', "bigger or equal sign"],
    ['=', "assign sign"],
    ['>>', "right stream"],
    ['|', "pipe"],
    ['$', "dollar"],
    ['.', "point"],
    ['\"', "double quote"],
    ["'", "single quote"],
]

# Tokens that don't fall into one of the above categories.
# "error" is for errors: when we encounter something unexpected.
# "whitespace" is the white space between tokens, and is explicit in our lexer.
tokens = [
    ["eof", ""],
    ["source file", ""],
    ["tombstone", ""],
    ["whitespace", "[ ]+"],
    ["comment", "#.*\\n"],
    ["newline", "\\n"],
    ["let stmt", ""],
    ["fn stmt", ""],
    ["cmd stmt", ""],
    ["math expr", ""],
    ["double quoted string", ""],
    ["single quoted string", ""],
    ["value path", ""],
    ["signature", ""],
    ["array", ""],
    ["table", ""],
    #meta rules
    ["value expr", ""],
    ["string expr", ""],
]

