syntax_elements = [
  # [kind_name                  , token_text , regex                                 , is_token , is_node , has_rule]

   # keywords
   [ "LetKeyword"               , "let"      , ""                                    , true     , false   , false]    ,
   [ "FnKeyword"                , "fn"       , ""                                    , true     , false   , false]    ,
   [ "ForKeyword"                , "for"       , ""                                    , true     , false   , false]    ,
   [ "ElifKeyword"              , "elif"     , ""                                    , true     , false   , false]    ,
   [ "ElseKeyword"              , "else"     , ""                                    , true     , false   , false]    ,
   [ "IfKeyword"                , "if"       , ""                                    , true     , false   , false]    ,
   [ "WhileKeyword"             , "while"    , ""                                    , true     , false   , false]    ,
   [ "EndKeyword"               , "end"      , ""                                    , true     , false   , false]    ,
   [ "BeginKeyword"               , "begin"      , ""                                    , true     , false   , false]    ,
   [ "InKeyword"               , "in"      , ""                                    , true     , false   , false]    ,

    # punctuation
    ["LeftParenthesis"          , '('        , ""                                    , true     , false   , false]    ,
    ["RightParenthesis"         , ')'        , ""                                    , true     , false,  false]  ,
    ["LeftCurlyBrackets"        , '{'        , ""                                    , true     , false   , false]    ,
    ["RightCurlyBrackets"       , '}'        , ""                                    , true     , false   , false]    ,
    ["LeftRectangularBrackets"  , '['        , ""                                    , true     , false   , false]    ,
    ["RightRectangularBrackets" , ']'        , ""                                    , true     , false   , false]    ,
    ["PlusSign"                 , '+'        , ""                                    , true     , false   , false]    ,
    ["MinusSign"                , '-'        , ""                                    , true     , false   , false]    ,
    ["MultSign"                 , '*'        , ""                                    , true     , false   , false]    ,
    ["DivSign"                  , '/'        , ""                                    , true     , false   , false]    ,
    ["LessThanSign"             , '<'        , ""                                    , true     , false   , false]    ,
    ["LessOrEqualSign"          , '<='       , ""                                    , true     , false   , false]    ,
    ["EqualitySign"             , '=='       , ""                                    , true     , false   , false]    ,
    ["InequalitySign"           , '!='       , ""                                    , true     , false   , false]    ,
    ["BiggerThanSign"           , '>'        , ""                                    , true     , false   , false]    ,
    ["BiggerOrEqualSign"        , '>='       , ""                                    , true     , false   , false]    ,
    ["AssignSign"               , '='        , ""                                    , true     , false   , false]    ,
    ["RightStream"              , '>>'       , ""                                    , true     , false   , false]    ,
    ["Pipe"                     , '|'        , ""                                    , true     , false   , false]    ,
    ["Dollar"                   , '$'        , ""                                    , true     , false   , false]    ,
    ["Point"                    , '.'        , ""                                    , true     , false   , false]    ,
    ["DoubleQuote"              , '\"'       , ""                                    , true     , false   , false]    ,
    ["SingleQuote"              , "'"        , ""                                    , true     , false   , false]    ,

    # various tokens
    ["Error"                    , ""         , ""                                    , true     , false   , false]    ,
    ["ParserInternal"                    , ""         , ""                                    , true     , false   , false]    ,
    ["BareWord"                 , ""         , "[_a-zA-Z]+"                           , true     , false   , false]    ,
    ["Whitespace"               , ""         , "[ ]+"                                , true     , false   , false]    ,
    ["Comment"                  , ""         , "#.*\\n"                              , true     , false   , false]    ,
    ["Newline"                  , ""         , "\\n"                                 , true     , false   , false]    ,
    ["Number"                   , ""         , "[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)" , true     , false   , false]    ,
    ["VarDeclName"                      , ""         , ""                                    , true    , false    , false]    ,

    #meta rules
    ["Eof"                      , ""         , ""                                    , false    , true    , false]    ,
    ["SourceFile"               , ""         , ""                                    , false    , true    , true]    ,
    ["Tombstone"                , ""         , ""                                    , false    , true    , false]    ,
    ["LetStmt"                  , ""         , ""                                    , false    , true    , true]    ,
    ["FnStmt"                   , ""         , ""                                    , false    , true    , true]    ,
    ["IfStmt"                   , ""         , ""                                    , false    , true    , true]    ,
    ["IfBlock"                   , ""         , ""                                    , false    , true    , false]    ,
    ["ElifBlock"                   , ""         , ""                                    , false    , true    , false]    ,
    ["ElseBlock"                   , ""         , ""                                    , false    , true    , false]    ,
    ["ForStmt"                   , ""         , ""                                    , false    , true    , true]    ,
    ["CmdStmt"                  , ""         , ""                                    , false    , true    , true]    ,
    ["BlockStmt"                  , ""         , ""                                    , false    , true    , true]    ,
    ["Signature"                , ""         , ""                                    , false    , true    , true]    ,
    ["MathExpr"                 , ""         , ""                                    , false    , true    , false]    , # TODO MathExprRule is not yet taken out of pratt parsing.. But could be
    ["StringExpr"               , ""         , ""                                    , false    , true    , true]    ,
    ["NumberExpr"               , ""         , ""                                    , false    , true    , true]    ,
    ["StringContent"            , ""         , ""                                    , true     , false   , false]    ,
    ["ValuePathExpr"            , ""         , ""                                    , false    , true    , true]    ,
    ["ArrayExpr"                , ""         , ""                                    , false    , true    , true]    ,
    ["TableExpr"                , ""         , ""                                    , false    , true    , true]    ,
]


# Elements that can be one of the above (represented as enums)
generic_elements = [
    # Element name, can represent, has_rule

    ["ValueExpr", ["BareWord", "NumberExpr", "MathExpr", "StringExpr", "ValuePathExpr", "ArrayExpr", "TableExpr"], true],
    ["Statement" , ["ForStmt", "LetStmt" , "FnStmt", "IfStmt", "CmdStmt"], true],
    ["Condition" , ["CmdStmt", "ValueExpr"], true],
]
